FROM openjdk:14-jdk-alpine
WORKDIR /app
ARG MYSQL_URL
ARG MYSQL_USERNAME
ARG MYSQL_PASSWORD
ARG MONGO_URL
ENV MYSQL_URL=$MYSQL_URL
ENV MYSQL_USERNAME=$MYSQL_USERNAME
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MONGO_URL=$MONGO_URL
COPY target/*.jar /app
ENTRYPOINT ["java", "-jar", "demo-0.0.1-SNAPSHOT.jar"]
EXPOSE 80
